In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM, SimpleRNN, Dropout, Flatten
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing import sequence

In [3]:
df = pd.read_csv('Walmart.csv')

In [4]:
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [5]:
df.Date=pd.to_datetime(df.Date)

df['weekday'] = df.Date.dt.weekday
df['month'] = df.Date.dt.month
df['year'] = df.Date.dt.year

In [6]:
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,weekday,month,year
0,1,2010-05-02,1643690.90,0,42.31,2.572,211.096358,8.106,6,5,2010
1,1,2010-12-02,1641957.44,1,38.51,2.548,211.242170,8.106,3,12,2010
2,1,2010-02-19,1611968.17,0,39.93,2.514,211.289143,8.106,4,2,2010
3,1,2010-02-26,1409727.59,0,46.63,2.561,211.319643,8.106,4,2,2010
4,1,2010-05-03,1554806.68,0,46.50,2.625,211.350143,8.106,0,5,2010

In [7]:
df.drop(['Date'], axis=1, inplace=True)#,'month'

df.head()

,Store,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,weekday,month,year
0,1,1643690.90,0,42.31,2.572,211.096358,8.106,6,5,2010
1,1,1641957.44,1,38.51,2.548,211.242170,8.106,3,12,2010
2,1,1611968.17,0,39.93,2.514,211.289143,8.106,4,2,2010
3,1,1409727.59,0,46.63,2.561,211.319643,8.106,4,2,2010
4,1,1554806.68,0,46.50,2.625,211.350143,8.106,0,5,2010

In [8]:
x=df.drop('Weekly_Sales',axis=1)
y=df['Weekly_Sales']

In [9]:
y=np.array(y)

In [10]:
from sklearn.preprocessing import MinMaxScaler
sc =MinMaxScaler()
x = sc.fit_transform(x)
y = sc.fit_transform(y.reshape(-1,1))

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [12]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((4504, 9), (1931, 9), (4504, 1), (1931, 1))

In [13]:
model = Sequential()

model.add(LSTM(100, return_sequences= True , input_shape = (9,1)))
model.add(Dropout(0.2))

model.add(LSTM(200, return_sequences= True ))
model.add(Dropout(0.2))

model.add(LSTM(200, return_sequences= True ))
model.add(Dropout(0.2))

model.add(LSTM(100 ))
model.add(Flatten())
model.add(Dense(1, activation='linear'))

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 lstm (LSTM)                 (None, 9, 100)            40800

 dropout (Dropout)           (None, 9, 100)            0

 lstm_1 (LSTM)               (None, 9, 200)            240800

 dropout_1 (Dropout)         (None, 9, 200)            0

 lstm_2 (LSTM)               (None, 9, 200)            320800

 dropout_2 (Dropout)         (None, 9, 200)            0

 lstm_3 (LSTM)               (None, 100)               120400

 flatten (Flatten)           (None, 100)               0

 dense (Dense)               (None, 1)                 101

=================================================================
Total params: 722,901
Trainable params: 722,901
Non-trainable params: 0
_________________________________________________________________

In [15]:
model.compile(loss='mae', optimizer='adam')

In [16]:
model_history = model.fit(x_train, y_train, epochs=100, batch_size=32)

Epoch 1/100
141/141 [==============================] - 8s 15ms/step - loss: 0.1305
Epoch 2/100
141/141 [==============================] - 2s 13ms/step - loss: 0.1252
Epoch 3/100
141/141 [==============================] - 2s 12ms/step - loss: 0.1239
Epoch 4/100
141/141 [==============================] - 2s 12ms/step - loss: 0.1230
Epoch 5/100
141/141 [==============================] - 8s 54ms/step - loss: 0.1228
Epoch 6/100
141/141 [==============================] - 7s 51ms/step - loss: 0.1229
Epoch 7/100
141/141 [==============================] - 5s 32ms/step - loss: 0.1228
Epoch 8/100
141/141 [==============================] - 4s 31ms/step - loss: 0.1225
Epoch 9/100
141/141 [==============================] - 4s 30ms/step - loss: 0.1234
Epoch 10/100
141/141 [==============================] - 4s 31ms/step - loss: 0.1222
Epoch 11/100
141/141 [==============================] - 5s 32ms/step - loss: 0.1219
Epoch 12/100
141/141 [==============================] - 4s 30ms/step - loss: 0.1224
Epoch 13/100
141/141 [==============================] - 4s 30ms/step - loss: 0.1224
Epoch 14/100
141/141 [==============================] - 4s 31ms/step - loss: 0.1211
Epoch 15/100
141/141 [==============================] - 4s 31ms/step - loss: 0.1176
Epoch 16/100
141/141 [==============================] - 4s 30ms/step - loss: 0.1152
Epoch 17/100
141/141 [==============================] - 4s 28ms/step - loss: 0.1145
Epoch 18/100
141/141 [==============================] - 4s 27ms/step - loss: 0.1128
Epoch 19/100
141/141 [==============================] - 4s 28ms/step - loss: 0.1109
Epoch 20/100
141/141 [==============================] - 4s 27ms/step - loss: 0.1096
Epoch 21/100
141/141 [==============================] - 4s 27ms/step - loss: 0.1083
Epoch 22/100
141/141 [==============================] - 4s 26ms/step - loss: 0.1081
Epoch 23/100
141/141 [==============================] - 4s 28ms/step - loss: 0.1063
Epoch 24/100
141/141 [==============================] - 4s 27ms/step - loss: 0.1039
Epoch 25/100
141/141 [==============================] - 4s 27ms/step - loss: 0.1023
Epoch 26/100
141/141 [==============================] - 4s 31ms/step - loss: 0.0993
Epoch 27/100
141/141 [==============================] - 4s 32ms/step - loss: 0.0970
Epoch 28/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0934
Epoch 29/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0924
Epoch 30/100
141/141 [==============================] - 4s 31ms/step - loss: 0.0889
Epoch 31/100
141/141 [==============================] - 4s 31ms/step - loss: 0.0859
Epoch 32/100
141/141 [==============================] - 4s 29ms/step - loss: 0.0891
Epoch 33/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0840
Epoch 34/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0834
Epoch 35/100
141/141 [==============================] - 4s 31ms/step - loss: 0.0832
Epoch 36/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0782
Epoch 37/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0839
Epoch 38/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0779
Epoch 39/100
141/141 [==============================] - 4s 31ms/step - loss: 0.0728
Epoch 40/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0715
Epoch 41/100
141/141 [==============================] - 4s 29ms/step - loss: 0.0713
Epoch 42/100
141/141 [==============================] - 4s 32ms/step - loss: 0.0713
Epoch 43/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0632
Epoch 44/100
141/141 [==============================] - 4s 29ms/step - loss: 0.0621
Epoch 45/100
141/141 [==============================] - 4s 32ms/step - loss: 0.0645
Epoch 46/100
141/141 [==============================] - 4s 31ms/step - loss: 0.0607
Epoch 47/100
141/141 [==============================] - 4s 29ms/step - loss: 0.0589
Epoch 48/100
141/141 [==============================] - 4s 29ms/step - loss: 0.0637
Epoch 49/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0566
Epoch 50/100
141/141 [==============================] - 4s 31ms/step - loss: 0.0540
Epoch 51/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0547
Epoch 52/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0527
Epoch 53/100
141/141 [==============================] - 4s 31ms/step - loss: 0.0611
Epoch 54/100
141/141 [==============================] - 4s 31ms/step - loss: 0.0507
Epoch 55/100
141/141 [==============================] - 4s 29ms/step - loss: 0.0559
Epoch 56/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0622
Epoch 57/100
141/141 [==============================] - 4s 31ms/step - loss: 0.0521
Epoch 58/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0501
Epoch 59/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0556
Epoch 60/100
141/141 [==============================] - 4s 31ms/step - loss: 0.0505
Epoch 61/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0476
Epoch 62/100
141/141 [==============================] - 4s 29ms/step - loss: 0.0544
Epoch 63/100
141/141 [==============================] - 4s 29ms/step - loss: 0.0524
Epoch 64/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0539
Epoch 65/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0481
Epoch 66/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0503
Epoch 67/100
141/141 [==============================] - 4s 29ms/step - loss: 0.0539
Epoch 68/100
141/141 [==============================] - 4s 31ms/step - loss: 0.0436
Epoch 69/100
141/141 [==============================] - 4s 31ms/step - loss: 0.0457
Epoch 70/100
141/141 [==============================] - 4s 28ms/step - loss: 0.0423
Epoch 71/100
141/141 [==============================] - 4s 28ms/step - loss: 0.0406
Epoch 72/100
141/141 [==============================] - 4s 31ms/step - loss: 0.0396
Epoch 73/100
141/141 [==============================] - 4s 27ms/step - loss: 0.0445
Epoch 74/100
141/141 [==============================] - 4s 25ms/step - loss: 0.0461
Epoch 75/100
141/141 [==============================] - 4s 29ms/step - loss: 0.0451
Epoch 76/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0421
Epoch 77/100
141/141 [==============================] - 4s 28ms/step - loss: 0.0364
Epoch 78/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0402
Epoch 79/100
141/141 [==============================] - 4s 31ms/step - loss: 0.0360
Epoch 80/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0525
Epoch 81/100
141/141 [==============================] - 4s 27ms/step - loss: 0.0437
Epoch 82/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0375
Epoch 83/100
141/141 [==============================] - 4s 31ms/step - loss: 0.0392
Epoch 84/100
141/141 [==============================] - 4s 31ms/step - loss: 0.0377
Epoch 85/100
141/141 [==============================] - 4s 25ms/step - loss: 0.0494
Epoch 86/100
141/141 [==============================] - 4s 27ms/step - loss: 0.0390
Epoch 87/100
141/141 [==============================] - 4s 26ms/step - loss: 0.0377
Epoch 88/100
141/141 [==============================] - 4s 31ms/step - loss: 0.0344
Epoch 89/100
141/141 [==============================] - 3s 24ms/step - loss: 0.0413
Epoch 90/100
141/141 [==============================] - 4s 26ms/step - loss: 0.0338
Epoch 91/100
141/141 [==============================] - 4s 28ms/step - loss: 0.0340
Epoch 92/100
141/141 [==============================] - 4s 28ms/step - loss: 0.0356
Epoch 93/100
141/141 [==============================] - 4s 27ms/step - loss: 0.0340
Epoch 94/100
141/141 [==============================] - 4s 27ms/step - loss: 0.0339
Epoch 95/100
141/141 [==============================] - 4s 30ms/step - loss: 0.0328
Epoch 96/100
141/141 [==============================] - 4s 31ms/step - loss: 0.0380
Epoch 97/100
141/141 [==============================] - 4s 29ms/step - loss: 0.0325
Epoch 98/100

141/141 [==============================] - 4s 26ms/step - loss: 0.0352
Epoch 99/100
141/141 [==============================] - 4s 28ms/step - loss: 0.0524
Epoch 100/100
141/141 [==============================] - 4s 29ms/step - loss: 0.0386

In [17]:
y_pred = model.predict(x_test)

In [18]:
from sklearn.metrics import r2_score

r2_score(y_test, y_pred)

0.7524621283494832

In [19]:
y_test[0]

array([0.46017482])

In [20]:
y_pred[0]

array([0.469649], dtype=float32)